# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letter',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='saved_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='sent_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='confirmed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscribed_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=256, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Last Name'),
        ),
    ]
