# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0002_auto_20171130_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='active',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=256, unique=True, verbose_name='E-mail'),
        ),
    ]
