# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_presenter_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='MC331', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
