# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170127_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.SmallIntegerField(choices=[(0, 'Seminar'), (1, 'Meeting'), (2, 'Lecture')], default=0),
        ),
    ]
