# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', '-start_time', '-end_time']},
        ),
        migrations.AddField(
            model_name='presenter',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
