# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170127_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenter',
            name='honorary',
            field=models.PositiveSmallIntegerField(choices=[(0, ''), (1, 'Dr.'), (2, 'Prof.')], default=0),
        ),
    ]
