# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_presenter_honorary'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Unnamed', max_length=128),
            preserve_default=False,
        ),
    ]
