# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenter',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
