# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20170128_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenter',
            name='presentation',
        ),
        migrations.AddField(
            model_name='presenter',
            name='presentation',
            field=models.ManyToManyField(to='events.Presentation'),
        ),
    ]
