# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20170128_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenter',
            name='affiliation',
        ),
        migrations.DeleteModel(
            name='Affiliation',
        ),
    ]
