# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_presenter_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenter',
            name='presentation',
            field=models.ManyToManyField(blank=True, to='events.Presentation'),
        ),
    ]
