# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20170128_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
    ]
