# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20170726_1340'),
        ('events', '0019_remove_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Room'),
        ),
    ]
