# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_added',
            new_name='date_created',
        ),
    ]
