# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20170801_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ics_file',
            field=models.FileField(blank=True, null=True, upload_to=events.models.event_ics_file),
        ),
    ]
