# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-11 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cses2019',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
