# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20170506_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentorganizer',
            name='bio',
            field=models.TextField(max_length=500),
        ),
    ]
