# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20170506_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentorganizer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
