# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_studentorganizer_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentorganizer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_organizers'),
        ),
    ]
