# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import research.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=128, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('site', models.URLField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('keywords', models.ManyToManyField(blank=True, to='research.Field')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=32)),
                ('img', models.ImageField(max_length=128, upload_to=research.models.image_file_path)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.Group')),
            ],
        ),
    ]
