# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='keywords',
            new_name='fields',
        ),
    ]
