# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20170811_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='field',
            old_name='keyword',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set([('group', 'tag')]),
        ),
    ]
