# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_field_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='css',
            field=models.TextField(blank=True, null=True),
        ),
    ]
