# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_image_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='css',
        ),
    ]
