# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='code',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
