# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20170726_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
